package com.expediente.clinico.model;
// Generated Dec 5, 2018 6:11:41 PM by Hibernate Tools 4.3.1



/**
 * Localidad generated by hbm2java
 */
public class Localidad  implements java.io.Serializable {


     private String codigo;
     private Municipio municipio;
     private String nombre;

    public Localidad() {
    }

    public Localidad(String codigo, Municipio municipio, String nombre) {
       this.codigo = codigo;
       this.municipio = municipio;
       this.nombre = nombre;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


