package com.expediente.clinico.model;
// Generated Dec 5, 2018 6:11:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private String codigo;
     private Estado estado;
     private String nombre;
     private Set localidads = new HashSet(0);

    public Municipio() {
    }

	
    public Municipio(String codigo, Estado estado, String nombre) {
        this.codigo = codigo;
        this.estado = estado;
        this.nombre = nombre;
    }
    public Municipio(String codigo, Estado estado, String nombre, Set localidads) {
       this.codigo = codigo;
       this.estado = estado;
       this.nombre = nombre;
       this.localidads = localidads;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getLocalidads() {
        return this.localidads;
    }
    
    public void setLocalidads(Set localidads) {
        this.localidads = localidads;
    }




}


